// <auto-generated />
namespace Hale.Core.Migrations.UserContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserContextInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserContextInit));
        
        string IMigrationMetadata.Id
        {
            get { return "201608111823433_UserContextInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
