// <auto-generated />
namespace Hale.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpdateModuleToRefAndAddThresholdsAndMissingCols : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateModuleToRefAndAddThresholdsAndMissingCols));
        
        string IMigrationMetadata.Id
        {
            get { return "201708101703304_UpdateModuleToRefAndAddThresholdsAndMissingCols"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
