//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Hale.Lib")]
[assembly: System.Reflection.AssemblyDescription("Hale.Lib")]
[assembly: System.Reflection.AssemblyProduct("Hale Monitoring")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2017, Hale Project")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.17218.5b50345")]
[assembly: System.Reflection.AssemblyVersion("1.0.17218")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.17218")]


